jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          cd ~/aws-s3-ec2-rds-cicd

          echo "Fetching tags..."
          git fetch --tags

          echo "Saving current version..."
          git rev-parse HEAD > prev_commit.txt

          echo "Deploying tag: $TAG_NAME"
          git checkout $TAG_NAME

          npm install
          npm run build

          npm run migration:run

          pm2 delete nest-app || true
          pm2 start ecosystem.config.js

          echo "Health check..."
          sleep 5

          for i in {1..5}; do
            curl -f http://localhost:3000/health && break
            sleep 2
          done || (

            echo "Deployment failed. Rolling back..."

            npm run migration:revert

            git checkout $(cat prev_commit.txt)

            npm install
            npm run build

            pm2 delete nest-app || true
            pm2 start ecosystem.config.js

            exit 1
          )

          echo "Deployment successful!"

          EOF