name: Deploy via Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (just for pipeline context)
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Deploy to EC2
        env:
          TAG_NAME: ${{ github.ref_name }}
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF

          cd ~/aws-s3-ec2-rds-cicd

          echo "=== Fetching latest tags ==="
          git fetch --tags

          echo "=== Moving to deployment folder ==="
          cd deployment

          echo "=== Saving previous version ==="
          if [ -f current_version.txt ]; then
            cp current_version.txt previous_version.txt
          fi

          echo "Previous version:"
          cat previous_version.txt || echo "None"

          echo "=== Deploying new version: $TAG_NAME ==="
          cd ~/aws-s3-ec2-rds-cicd
          git checkout $TAG_NAME

          echo "$TAG_NAME" > deployment/current_version.txt

          echo "=== Installing dependencies ==="
          npm install

          echo "=== Building app ==="
          npm run build

          echo "=== Running migrations ==="
          npm run migration:run

          echo "=== Restarting app ==="
          pm2 delete nest-app || true
          pm2 start ecosystem.config.js

          echo "=== Health check ==="
          sleep 5

          curl -f http://localhost:3000/health || (

            echo "❌ Deployment failed. Rolling back..."

            echo "Reverting DB..."
            npm run migration:revert

            echo "Rolling back code..."
            cd deployment
            PREV_VERSION=$(cat previous_version.txt)

            cd ~/aws-s3-ec2-rds-cicd
            git checkout $PREV_VERSION

            echo "Restoring version file to $PREV_VERSION...."
            echo "$PREV_VERSION" > deployment/current_version.txt

            echo "Re-installing..."
            npm install

            echo "Re-building..."
            npm run build

            echo "Restarting app..."
            pm2 delete nest-app || true
            pm2 start ecosystem.config.js

            echo "Rollback completed"

            exit 1
          )

          echo "✅ Deployment successful"

          EOF